//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASAMOTORS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-T0HOCLV;Initial Catalog=ServiceCenterManagementDB;Integrated " +
            "Security=True")]
        public string rasaMotorsConnectionString {
            get {
                return ((string)(this["rasaMotorsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]

       // [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CHARMINPC\\SQLEXPRESS;Initial Catalog=ServiceCenterManagementDB;Integr" +
         //   "ated Security=True")]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HEN8CVM;Initial Catalog=ServiceCenterManagementDB;Integrated " +
            "Security=True")]

        public string ServiceCenterManagementDBConnectionString {
            get {
                return ((string)(this["ServiceCenterManagementDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A6OVS3L\\SQLEXPRESS;Initial Catalog=NetProfit;Integrated Secur" +
            "ity=True")]
        public string NetProfitConnectionString {
            get {
                return ((string)(this["NetProfitConnectionString"]));
            }
        }
    }
}
